// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScanVul.Server.Infrastructure.Data;

#nullable disable

namespace ScanVul.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225123530_AddFalsePositiveColumnToVulnerablePackage")]
    partial class AddFalsePositiveColumnToVulnerablePackage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComputerPackageInfo", b =>
                {
                    b.Property<long>("ComputerId")
                        .HasColumnType("bigint")
                        .HasColumnName("computer_id");

                    b.Property<long>("PackagesId")
                        .HasColumnType("bigint")
                        .HasColumnName("packages_id");

                    b.HasKey("ComputerId", "PackagesId")
                        .HasName("pk_computer_package_info");

                    b.HasIndex("PackagesId")
                        .HasDatabaseName("ix_computer_package_info_packages_id");

                    b.ToTable("computer_package_info", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Agent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ComputerId")
                        .HasColumnType("bigint")
                        .HasColumnName("computer_id");

                    b.Property<DateTime>("LastPackagesScrapingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_packages_scraping_at");

                    b.Property<DateTime>("LastPingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ping_at");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("ComputerId")
                        .HasDatabaseName("ix_agents_computer_id");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Computer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CpuName")
                        .HasColumnType("text")
                        .HasColumnName("cpu_name");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<int?>("MemoryInMb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_in_mb");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OperatingSystem")
                        .HasColumnType("integer")
                        .HasColumnName("operating_system");

                    b.HasKey("Id")
                        .HasName("pk_computers");

                    b.ToTable("computers", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.PackageInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_package_infos");

                    b.HasIndex("Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_package_infos_name_version");

                    b.ToTable("package_infos", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.VulnerablePackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ComputerId")
                        .HasColumnType("bigint")
                        .HasColumnName("computer_id");

                    b.Property<string>("CveId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cve_id");

                    b.Property<bool>("IsFalsePositive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_false_positive");

                    b.Property<long>("PackageInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("package_info_id");

                    b.HasKey("Id")
                        .HasName("pk_vulnerable_packages");

                    b.HasIndex("ComputerId")
                        .HasDatabaseName("ix_vulnerable_packages_computer_id");

                    b.HasIndex("PackageInfoId", "CveId", "ComputerId")
                        .IsUnique()
                        .HasDatabaseName("ix_vulnerable_packages_package_info_id_cve_id_computer_id");

                    b.ToTable("vulnerable_packages", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.UserAggregate.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ComputerPackageInfo", b =>
                {
                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_computer_package_info_computers_computer_id");

                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.PackageInfo", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_computer_package_info_package_infos_packages_id");
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Agent", b =>
                {
                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.Computer", "Computer")
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agents_computers_computer_id");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.VulnerablePackage", b =>
                {
                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.Computer", "Computer")
                        .WithMany("VulnerablePackages")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vulnerable_packages_computers_computer_id");

                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.PackageInfo", "PackageInfo")
                        .WithMany()
                        .HasForeignKey("PackageInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vulnerable_packages_package_infos_package_info_id");

                    b.Navigation("Computer");

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Computer", b =>
                {
                    b.Navigation("VulnerablePackages");
                });
#pragma warning restore 612, 618
        }
    }
}
