// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using ScanVul.Server.Infrastructure.Data;

#nullable disable

namespace ScanVul.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419200119_AddScanSnapshot")]
    partial class AddScanSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComputerPackageInfo", b =>
                {
                    b.Property<long>("ComputerId")
                        .HasColumnType("bigint")
                        .HasColumnName("computer_id");

                    b.Property<long>("PackagesId")
                        .HasColumnType("bigint")
                        .HasColumnName("packages_id");

                    b.HasKey("ComputerId", "PackagesId")
                        .HasName("pk_computer_package_info");

                    b.HasIndex("PackagesId")
                        .HasDatabaseName("ix_computer_package_info_packages_id");

                    b.ToTable("computer_package_info", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Agent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ComputerId")
                        .HasColumnType("bigint")
                        .HasColumnName("computer_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastPackagesScrapingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_packages_scraping_at");

                    b.Property<DateTime>("LastPingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ping_at");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("ComputerId")
                        .HasDatabaseName("ix_agents_computer_id");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.BduVulnerablePackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ComputerId")
                        .HasColumnType("bigint")
                        .HasColumnName("computer_id");

                    b.Property<bool>("IsFalsePositive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_false_positive");

                    b.Property<bool>("IsPatchless")
                        .HasColumnType("boolean")
                        .HasColumnName("is_patchless");

                    b.Property<long>("PackageInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("package_info_id");

                    b.Property<string>("VulnerabilityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vulnerability_id");

                    b.HasKey("Id")
                        .HasName("pk_bdu_vulnerable_packages");

                    b.HasIndex("ComputerId")
                        .HasDatabaseName("ix_bdu_vulnerable_packages_computer_id");

                    b.HasIndex("PackageInfoId", "VulnerabilityId", "ComputerId")
                        .IsUnique()
                        .HasDatabaseName("ix_bdu_vulnerable_packages_package_info_id_vulnerability_id_co");

                    b.ToTable("bdu_vulnerable_packages", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Commands.AgentCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentResponse")
                        .HasColumnType("text")
                        .HasColumnName("agent_response");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_agent_command");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_agent_command_agent_id");

                    b.ToTable("agent_command", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Computer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CpuName")
                        .HasColumnType("text")
                        .HasColumnName("cpu_name");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<int?>("MemoryInMb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_in_mb");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OperatingSystem")
                        .HasColumnType("integer")
                        .HasColumnName("operating_system");

                    b.HasKey("Id")
                        .HasName("pk_computers");

                    b.ToTable("computers", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.PackageInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_package_infos");

                    b.HasIndex("Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_package_infos_name_version");

                    b.ToTable("package_infos", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ComputerId")
                        .HasColumnType("bigint")
                        .HasColumnName("computer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LastDiffId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_diff_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "BduVulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.BduVulnerablePackages#BduVulnerablePackage", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<long>("ComputerId");

                                    b2.Property<long>("Id");

                                    b2.Property<bool>("IsFalsePositive");

                                    b2.Property<bool>("IsPatchless");

                                    b2.Property<long>("PackageInfoId");

                                    b2.Property<string>("VulnerabilityId")
                                        .IsRequired();

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Computer", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.BduVulnerablePackages#BduVulnerablePackage.Computer#Computer", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("CpuName");

                                            b3.Property<long>("Id");

                                            b3.Property<IPAddress>("IpAddress")
                                                .IsRequired();

                                            b3.Property<int?>("MemoryInMb");

                                            b3.Property<string>("Name");

                                            b3.Property<int>("OperatingSystem");

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "Packages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.BduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Packages#PackageInfo", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("Id");

                                                    b4.Property<string>("Name")
                                                        .IsRequired();

                                                    b4.Property<string>("Version")
                                                        .IsRequired();
                                                });

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "VulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.BduVulnerablePackages#BduVulnerablePackage.Computer#Computer.VulnerablePackages#VulnerablePackage", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("ComputerId");

                                                    b4.Property<long>("Id");

                                                    b4.Property<bool>("IsFalsePositive");

                                                    b4.Property<bool>("IsPatchless");

                                                    b4.Property<long>("PackageInfoId");

                                                    b4.Property<string>("VulnerabilityId")
                                                        .IsRequired();

                                                    b4.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.BduVulnerablePackages#BduVulnerablePackage.Computer#Computer.VulnerablePackages#VulnerablePackage.PackageInfo#PackageInfo", b5 =>
                                                        {
                                                            b5.IsRequired();

                                                            b5.Property<long>("Id");

                                                            b5.Property<string>("Name")
                                                                .IsRequired();

                                                            b5.Property<string>("Version")
                                                                .IsRequired();
                                                        });
                                                });
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.BduVulnerablePackages#BduVulnerablePackage.PackageInfo#PackageInfo", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<long>("Id");

                                            b3.Property<string>("Name")
                                                .IsRequired();

                                            b3.Property<string>("Version")
                                                .IsRequired();
                                        });
                                });

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Packages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.Packages#PackageInfo", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<long>("Id");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Version")
                                        .IsRequired();
                                });

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "VulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.VulnerablePackages#VulnerablePackage", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<long>("ComputerId");

                                    b2.Property<long>("Id");

                                    b2.Property<bool>("IsFalsePositive");

                                    b2.Property<bool>("IsPatchless");

                                    b2.Property<long>("PackageInfoId");

                                    b2.Property<string>("VulnerabilityId")
                                        .IsRequired();

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Computer", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.VulnerablePackages#VulnerablePackage.Computer#Computer", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("CpuName");

                                            b3.Property<long>("Id");

                                            b3.Property<IPAddress>("IpAddress")
                                                .IsRequired();

                                            b3.Property<int?>("MemoryInMb");

                                            b3.Property<string>("Name");

                                            b3.Property<int>("OperatingSystem");

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "BduVulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.VulnerablePackages#VulnerablePackage.Computer#Computer.BduVulnerablePackages#BduVulnerablePackage", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("ComputerId");

                                                    b4.Property<long>("Id");

                                                    b4.Property<bool>("IsFalsePositive");

                                                    b4.Property<bool>("IsPatchless");

                                                    b4.Property<long>("PackageInfoId");

                                                    b4.Property<string>("VulnerabilityId")
                                                        .IsRequired();

                                                    b4.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.VulnerablePackages#VulnerablePackage.Computer#Computer.BduVulnerablePackages#BduVulnerablePackage.PackageInfo#PackageInfo", b5 =>
                                                        {
                                                            b5.IsRequired();

                                                            b5.Property<long>("Id");

                                                            b5.Property<string>("Name")
                                                                .IsRequired();

                                                            b5.Property<string>("Version")
                                                                .IsRequired();
                                                        });
                                                });

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "Packages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.VulnerablePackages#VulnerablePackage.Computer#Computer.Packages#PackageInfo", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("Id");

                                                    b4.Property<string>("Name")
                                                        .IsRequired();

                                                    b4.Property<string>("Version")
                                                        .IsRequired();
                                                });
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot.Payload#ScanSnapshotPayload.VulnerablePackages#VulnerablePackage.PackageInfo#PackageInfo", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<long>("Id");

                                            b3.Property<string>("Name")
                                                .IsRequired();

                                            b3.Property<string>("Version")
                                                .IsRequired();
                                        });
                                });

                            b1
                                .ToJson("payload")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_scan_snapshot");

                    b.HasIndex("ComputerId")
                        .HasDatabaseName("ix_scan_snapshot_computer_id");

                    b.HasIndex("LastDiffId")
                        .HasDatabaseName("ix_scan_snapshot_last_diff_id");

                    b.ToTable("scan_snapshot", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FirstSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_snapshot_id");

                    b.Property<Guid>("SecondSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("second_snapshot_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "AddedBduVulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedBduVulnerablePackages#BduVulnerablePackage", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<long>("ComputerId");

                                    b2.Property<long>("Id");

                                    b2.Property<bool>("IsFalsePositive");

                                    b2.Property<bool>("IsPatchless");

                                    b2.Property<long>("PackageInfoId");

                                    b2.Property<string>("VulnerabilityId")
                                        .IsRequired();

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Computer", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("CpuName");

                                            b3.Property<long>("Id");

                                            b3.Property<IPAddress>("IpAddress")
                                                .IsRequired();

                                            b3.Property<int?>("MemoryInMb");

                                            b3.Property<string>("Name");

                                            b3.Property<int>("OperatingSystem");

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "Packages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Packages#PackageInfo", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("Id");

                                                    b4.Property<string>("Name")
                                                        .IsRequired();

                                                    b4.Property<string>("Version")
                                                        .IsRequired();
                                                });

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "Snapshots", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("ComputerId");

                                                    b4.Property<DateTime>("CreatedAt");

                                                    b4.Property<Guid>("Id");

                                                    b4.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload", b5 =>
                                                        {
                                                            b5.IsRequired();

                                                            b5.ComplexCollection(typeof(List<Dictionary<string, object>>), "Packages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload.Packages#PackageInfo", b6 =>
                                                                {
                                                                    b6.IsRequired();

                                                                    b6.Property<long>("Id");

                                                                    b6.Property<string>("Name")
                                                                        .IsRequired();

                                                                    b6.Property<string>("Version")
                                                                        .IsRequired();
                                                                });

                                                            b5.ComplexCollection(typeof(List<Dictionary<string, object>>), "VulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload.VulnerablePackages#VulnerablePackage", b6 =>
                                                                {
                                                                    b6.IsRequired();

                                                                    b6.Property<long>("ComputerId");

                                                                    b6.Property<long>("Id");

                                                                    b6.Property<bool>("IsFalsePositive");

                                                                    b6.Property<bool>("IsPatchless");

                                                                    b6.Property<long>("PackageInfoId");

                                                                    b6.Property<string>("VulnerabilityId")
                                                                        .IsRequired();

                                                                    b6.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload.VulnerablePackages#VulnerablePackage.PackageInfo#PackageInfo", b7 =>
                                                                        {
                                                                            b7.IsRequired();

                                                                            b7.Property<long>("Id");

                                                                            b7.Property<string>("Name")
                                                                                .IsRequired();

                                                                            b7.Property<string>("Version")
                                                                                .IsRequired();
                                                                        });
                                                                });
                                                        });
                                                });

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "VulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.VulnerablePackages#VulnerablePackage", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("ComputerId");

                                                    b4.Property<long>("Id");

                                                    b4.Property<bool>("IsFalsePositive");

                                                    b4.Property<bool>("IsPatchless");

                                                    b4.Property<long>("PackageInfoId");

                                                    b4.Property<string>("VulnerabilityId")
                                                        .IsRequired();

                                                    b4.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.VulnerablePackages#VulnerablePackage.PackageInfo#PackageInfo", b5 =>
                                                        {
                                                            b5.IsRequired();

                                                            b5.Property<long>("Id");

                                                            b5.Property<string>("Name")
                                                                .IsRequired();

                                                            b5.Property<string>("Version")
                                                                .IsRequired();
                                                        });
                                                });
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedBduVulnerablePackages#BduVulnerablePackage.PackageInfo#PackageInfo", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<long>("Id");

                                            b3.Property<string>("Name")
                                                .IsRequired();

                                            b3.Property<string>("Version")
                                                .IsRequired();
                                        });
                                });

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "AddedPackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedPackages#PackageInfo", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<long>("Id");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Version")
                                        .IsRequired();
                                });

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "AddedVulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedVulnerablePackages#VulnerablePackage", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<long>("ComputerId");

                                    b2.Property<long>("Id");

                                    b2.Property<bool>("IsFalsePositive");

                                    b2.Property<bool>("IsPatchless");

                                    b2.Property<long>("PackageInfoId");

                                    b2.Property<string>("VulnerabilityId")
                                        .IsRequired();

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Computer", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedVulnerablePackages#VulnerablePackage.Computer#Computer", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("CpuName");

                                            b3.Property<long>("Id");

                                            b3.Property<IPAddress>("IpAddress")
                                                .IsRequired();

                                            b3.Property<int?>("MemoryInMb");

                                            b3.Property<string>("Name");

                                            b3.Property<int>("OperatingSystem");

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "BduVulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedVulnerablePackages#VulnerablePackage.Computer#Computer.BduVulnerablePackages#BduVulnerablePackage", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("ComputerId");

                                                    b4.Property<long>("Id");

                                                    b4.Property<bool>("IsFalsePositive");

                                                    b4.Property<bool>("IsPatchless");

                                                    b4.Property<long>("PackageInfoId");

                                                    b4.Property<string>("VulnerabilityId")
                                                        .IsRequired();

                                                    b4.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedVulnerablePackages#VulnerablePackage.Computer#Computer.BduVulnerablePackages#BduVulnerablePackage.PackageInfo#PackageInfo", b5 =>
                                                        {
                                                            b5.IsRequired();

                                                            b5.Property<long>("Id");

                                                            b5.Property<string>("Name")
                                                                .IsRequired();

                                                            b5.Property<string>("Version")
                                                                .IsRequired();
                                                        });
                                                });

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "Packages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedVulnerablePackages#VulnerablePackage.Computer#Computer.Packages#PackageInfo", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("Id");

                                                    b4.Property<string>("Name")
                                                        .IsRequired();

                                                    b4.Property<string>("Version")
                                                        .IsRequired();
                                                });

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "Snapshots", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedVulnerablePackages#VulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("ComputerId");

                                                    b4.Property<DateTime>("CreatedAt");

                                                    b4.Property<Guid>("Id");

                                                    b4.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedVulnerablePackages#VulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload", b5 =>
                                                        {
                                                            b5.IsRequired();

                                                            b5.ComplexCollection(typeof(List<Dictionary<string, object>>), "BduVulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedVulnerablePackages#VulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload.BduVulnerablePackages#BduVulnerablePackage", b6 =>
                                                                {
                                                                    b6.IsRequired();

                                                                    b6.Property<long>("ComputerId");

                                                                    b6.Property<long>("Id");

                                                                    b6.Property<bool>("IsFalsePositive");

                                                                    b6.Property<bool>("IsPatchless");

                                                                    b6.Property<long>("PackageInfoId");

                                                                    b6.Property<string>("VulnerabilityId")
                                                                        .IsRequired();

                                                                    b6.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedVulnerablePackages#VulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload.BduVulnerablePackages#BduVulnerablePackage.PackageInfo#PackageInfo", b7 =>
                                                                        {
                                                                            b7.IsRequired();

                                                                            b7.Property<long>("Id");

                                                                            b7.Property<string>("Name")
                                                                                .IsRequired();

                                                                            b7.Property<string>("Version")
                                                                                .IsRequired();
                                                                        });
                                                                });

                                                            b5.ComplexCollection(typeof(List<Dictionary<string, object>>), "Packages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedVulnerablePackages#VulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload.Packages#PackageInfo", b6 =>
                                                                {
                                                                    b6.IsRequired();

                                                                    b6.Property<long>("Id");

                                                                    b6.Property<string>("Name")
                                                                        .IsRequired();

                                                                    b6.Property<string>("Version")
                                                                        .IsRequired();
                                                                });
                                                        });
                                                });
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.AddedVulnerablePackages#VulnerablePackage.PackageInfo#PackageInfo", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<long>("Id");

                                            b3.Property<string>("Name")
                                                .IsRequired();

                                            b3.Property<string>("Version")
                                                .IsRequired();
                                        });
                                });

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "RemovedBduVulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedBduVulnerablePackages#BduVulnerablePackage", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<long>("ComputerId");

                                    b2.Property<long>("Id");

                                    b2.Property<bool>("IsFalsePositive");

                                    b2.Property<bool>("IsPatchless");

                                    b2.Property<long>("PackageInfoId");

                                    b2.Property<string>("VulnerabilityId")
                                        .IsRequired();

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Computer", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("CpuName");

                                            b3.Property<long>("Id");

                                            b3.Property<IPAddress>("IpAddress")
                                                .IsRequired();

                                            b3.Property<int?>("MemoryInMb");

                                            b3.Property<string>("Name");

                                            b3.Property<int>("OperatingSystem");

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "Packages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Packages#PackageInfo", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("Id");

                                                    b4.Property<string>("Name")
                                                        .IsRequired();

                                                    b4.Property<string>("Version")
                                                        .IsRequired();
                                                });

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "Snapshots", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("ComputerId");

                                                    b4.Property<DateTime>("CreatedAt");

                                                    b4.Property<Guid>("Id");

                                                    b4.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload", b5 =>
                                                        {
                                                            b5.IsRequired();

                                                            b5.ComplexCollection(typeof(List<Dictionary<string, object>>), "Packages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload.Packages#PackageInfo", b6 =>
                                                                {
                                                                    b6.IsRequired();

                                                                    b6.Property<long>("Id");

                                                                    b6.Property<string>("Name")
                                                                        .IsRequired();

                                                                    b6.Property<string>("Version")
                                                                        .IsRequired();
                                                                });

                                                            b5.ComplexCollection(typeof(List<Dictionary<string, object>>), "VulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload.VulnerablePackages#VulnerablePackage", b6 =>
                                                                {
                                                                    b6.IsRequired();

                                                                    b6.Property<long>("ComputerId");

                                                                    b6.Property<long>("Id");

                                                                    b6.Property<bool>("IsFalsePositive");

                                                                    b6.Property<bool>("IsPatchless");

                                                                    b6.Property<long>("PackageInfoId");

                                                                    b6.Property<string>("VulnerabilityId")
                                                                        .IsRequired();

                                                                    b6.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload.VulnerablePackages#VulnerablePackage.PackageInfo#PackageInfo", b7 =>
                                                                        {
                                                                            b7.IsRequired();

                                                                            b7.Property<long>("Id");

                                                                            b7.Property<string>("Name")
                                                                                .IsRequired();

                                                                            b7.Property<string>("Version")
                                                                                .IsRequired();
                                                                        });
                                                                });
                                                        });
                                                });

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "VulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.VulnerablePackages#VulnerablePackage", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("ComputerId");

                                                    b4.Property<long>("Id");

                                                    b4.Property<bool>("IsFalsePositive");

                                                    b4.Property<bool>("IsPatchless");

                                                    b4.Property<long>("PackageInfoId");

                                                    b4.Property<string>("VulnerabilityId")
                                                        .IsRequired();

                                                    b4.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedBduVulnerablePackages#BduVulnerablePackage.Computer#Computer.VulnerablePackages#VulnerablePackage.PackageInfo#PackageInfo", b5 =>
                                                        {
                                                            b5.IsRequired();

                                                            b5.Property<long>("Id");

                                                            b5.Property<string>("Name")
                                                                .IsRequired();

                                                            b5.Property<string>("Version")
                                                                .IsRequired();
                                                        });
                                                });
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedBduVulnerablePackages#BduVulnerablePackage.PackageInfo#PackageInfo", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<long>("Id");

                                            b3.Property<string>("Name")
                                                .IsRequired();

                                            b3.Property<string>("Version")
                                                .IsRequired();
                                        });
                                });

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "RemovedPackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedPackages#PackageInfo", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<long>("Id");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Version")
                                        .IsRequired();
                                });

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "RemovedVulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedVulnerablePackages#VulnerablePackage", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<long>("ComputerId");

                                    b2.Property<long>("Id");

                                    b2.Property<bool>("IsFalsePositive");

                                    b2.Property<bool>("IsPatchless");

                                    b2.Property<long>("PackageInfoId");

                                    b2.Property<string>("VulnerabilityId")
                                        .IsRequired();

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Computer", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedVulnerablePackages#VulnerablePackage.Computer#Computer", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("CpuName");

                                            b3.Property<long>("Id");

                                            b3.Property<IPAddress>("IpAddress")
                                                .IsRequired();

                                            b3.Property<int?>("MemoryInMb");

                                            b3.Property<string>("Name");

                                            b3.Property<int>("OperatingSystem");

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "BduVulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedVulnerablePackages#VulnerablePackage.Computer#Computer.BduVulnerablePackages#BduVulnerablePackage", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("ComputerId");

                                                    b4.Property<long>("Id");

                                                    b4.Property<bool>("IsFalsePositive");

                                                    b4.Property<bool>("IsPatchless");

                                                    b4.Property<long>("PackageInfoId");

                                                    b4.Property<string>("VulnerabilityId")
                                                        .IsRequired();

                                                    b4.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedVulnerablePackages#VulnerablePackage.Computer#Computer.BduVulnerablePackages#BduVulnerablePackage.PackageInfo#PackageInfo", b5 =>
                                                        {
                                                            b5.IsRequired();

                                                            b5.Property<long>("Id");

                                                            b5.Property<string>("Name")
                                                                .IsRequired();

                                                            b5.Property<string>("Version")
                                                                .IsRequired();
                                                        });
                                                });

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "Packages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedVulnerablePackages#VulnerablePackage.Computer#Computer.Packages#PackageInfo", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("Id");

                                                    b4.Property<string>("Name")
                                                        .IsRequired();

                                                    b4.Property<string>("Version")
                                                        .IsRequired();
                                                });

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "Snapshots", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedVulnerablePackages#VulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot", b4 =>
                                                {
                                                    b4.IsRequired();

                                                    b4.Property<long>("ComputerId");

                                                    b4.Property<DateTime>("CreatedAt");

                                                    b4.Property<Guid>("Id");

                                                    b4.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedVulnerablePackages#VulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload", b5 =>
                                                        {
                                                            b5.IsRequired();

                                                            b5.ComplexCollection(typeof(List<Dictionary<string, object>>), "BduVulnerablePackages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedVulnerablePackages#VulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload.BduVulnerablePackages#BduVulnerablePackage", b6 =>
                                                                {
                                                                    b6.IsRequired();

                                                                    b6.Property<long>("ComputerId");

                                                                    b6.Property<long>("Id");

                                                                    b6.Property<bool>("IsFalsePositive");

                                                                    b6.Property<bool>("IsPatchless");

                                                                    b6.Property<long>("PackageInfoId");

                                                                    b6.Property<string>("VulnerabilityId")
                                                                        .IsRequired();

                                                                    b6.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedVulnerablePackages#VulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload.BduVulnerablePackages#BduVulnerablePackage.PackageInfo#PackageInfo", b7 =>
                                                                        {
                                                                            b7.IsRequired();

                                                                            b7.Property<long>("Id");

                                                                            b7.Property<string>("Name")
                                                                                .IsRequired();

                                                                            b7.Property<string>("Version")
                                                                                .IsRequired();
                                                                        });
                                                                });

                                                            b5.ComplexCollection(typeof(List<Dictionary<string, object>>), "Packages", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedVulnerablePackages#VulnerablePackage.Computer#Computer.Snapshots#ScanSnapshot.Payload#ScanSnapshotPayload.Packages#PackageInfo", b6 =>
                                                                {
                                                                    b6.IsRequired();

                                                                    b6.Property<long>("Id");

                                                                    b6.Property<string>("Name")
                                                                        .IsRequired();

                                                                    b6.Property<string>("Version")
                                                                        .IsRequired();
                                                                });
                                                        });
                                                });
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "PackageInfo", "ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff.Payload#ScanSnapshotDiffPayload.RemovedVulnerablePackages#VulnerablePackage.PackageInfo#PackageInfo", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<long>("Id");

                                            b3.Property<string>("Name")
                                                .IsRequired();

                                            b3.Property<string>("Version")
                                                .IsRequired();
                                        });
                                });

                            b1
                                .ToJson("payload")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_scan_snapshot_diff");

                    b.HasIndex("FirstSnapshotId")
                        .HasDatabaseName("ix_scan_snapshot_diff_first_snapshot_id");

                    b.HasIndex("SecondSnapshotId")
                        .HasDatabaseName("ix_scan_snapshot_diff_second_snapshot_id");

                    b.ToTable("scan_snapshot_diff", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.VulnerablePackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ComputerId")
                        .HasColumnType("bigint")
                        .HasColumnName("computer_id");

                    b.Property<bool>("IsFalsePositive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_false_positive");

                    b.Property<bool>("IsPatchless")
                        .HasColumnType("boolean")
                        .HasColumnName("is_patchless");

                    b.Property<long>("PackageInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("package_info_id");

                    b.Property<string>("VulnerabilityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vulnerability_id");

                    b.HasKey("Id")
                        .HasName("pk_vulnerable_packages");

                    b.HasIndex("ComputerId")
                        .HasDatabaseName("ix_vulnerable_packages_computer_id");

                    b.HasIndex("PackageInfoId", "VulnerabilityId", "ComputerId")
                        .IsUnique()
                        .HasDatabaseName("ix_vulnerable_packages_package_info_id_vulnerability_id_comput");

                    b.ToTable("vulnerable_packages", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.PackageManagers.Entities.WingetPackage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<long>("IdRowId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_row_id");

                    b.Property<string>("LastVersion")
                        .HasColumnType("text")
                        .HasColumnName("last_version");

                    b.Property<long?>("LastVersionRowId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_version_row_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("NameRowId")
                        .HasColumnType("bigint")
                        .HasColumnName("name_row_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('english', coalesce(\"name\", '') || ' ' || coalesce(\"id\", ''))", true);

                    b.HasKey("Id")
                        .HasName("pk_winget_packages");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_winget_packages_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("winget_packages", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.Reports.Entities.VulnerabilityScanReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ObjectName")
                        .HasColumnType("text")
                        .HasColumnName("object_name");

                    b.HasKey("Id")
                        .HasName("pk_vulnerability_scan_reports");

                    b.ToTable("vulnerability_scan_reports", (string)null);
                });

            modelBuilder.Entity("ScanVul.Server.Domain.UserAggregate.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ComputerPackageInfo", b =>
                {
                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_computer_package_info_computers_computer_id");

                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.PackageInfo", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_computer_package_info_package_infos_packages_id");
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Agent", b =>
                {
                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.Computer", "Computer")
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agents_computers_computer_id");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.BduVulnerablePackage", b =>
                {
                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.Computer", "Computer")
                        .WithMany("BduVulnerablePackages")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bdu_vulnerable_packages_computers_computer_id");

                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.PackageInfo", "PackageInfo")
                        .WithMany()
                        .HasForeignKey("PackageInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bdu_vulnerable_packages_package_infos_package_info_id");

                    b.Navigation("Computer");

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Commands.AgentCommand", b =>
                {
                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.Agent", "Agent")
                        .WithMany("Commands")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_command_agents_agent_id");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot", b =>
                {
                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.Computer", "Computer")
                        .WithMany("Snapshots")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_snapshot_computers_computer_id");

                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff", "LastDiff")
                        .WithMany()
                        .HasForeignKey("LastDiffId")
                        .HasConstraintName("fk_scan_snapshot_scan_snapshot_diff_last_diff_id");

                    b.Navigation("Computer");

                    b.Navigation("LastDiff");
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshotDiff", b =>
                {
                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot", "FirstSnapshot")
                        .WithMany()
                        .HasForeignKey("FirstSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_snapshot_diff_scan_snapshot_first_snapshot_id");

                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.Snapshots.ScanSnapshot", "SecondSnapshot")
                        .WithMany()
                        .HasForeignKey("SecondSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_snapshot_diff_scan_snapshot_second_snapshot_id");

                    b.Navigation("FirstSnapshot");

                    b.Navigation("SecondSnapshot");
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.VulnerablePackage", b =>
                {
                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.Computer", "Computer")
                        .WithMany("VulnerablePackages")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vulnerable_packages_computers_computer_id");

                    b.HasOne("ScanVul.Server.Domain.AgentAggregate.Entities.PackageInfo", "PackageInfo")
                        .WithMany()
                        .HasForeignKey("PackageInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vulnerable_packages_package_infos_package_info_id");

                    b.Navigation("Computer");

                    b.Navigation("PackageInfo");
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Agent", b =>
                {
                    b.Navigation("Commands");
                });

            modelBuilder.Entity("ScanVul.Server.Domain.AgentAggregate.Entities.Computer", b =>
                {
                    b.Navigation("BduVulnerablePackages");

                    b.Navigation("Snapshots");

                    b.Navigation("VulnerablePackages");
                });
#pragma warning restore 612, 618
        }
    }
}
